apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: api-gateway
  name: api-gateway
spec:
  hostname: api-gateway
  containers:
  - image: vergeops/k8s-rvstore-api-gateway:1.0
    name: api-gateway
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: compose
    ports:
    - containerPort: 9000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
