apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: product
  name: product
spec:
  hostname: product
  containers:
  - image: vergeops/k8s-rvstore-product-api:1.0
    name: product
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: compose
    ports:
    - containerPort: 9001
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
