apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simulator
  name: simulator
spec:
  hostname: simulator
  containers:
  - image: vergeops/k8s-rvstore-order-simulator:1.0
    name: simulator
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: compose
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
